#+TITLE: Posts

- [[file:2020-02-08-Stackable-Things/index.org][On the beauty of stackable things]]
- [[file:2020-02-02-Awesome-list-of-text-to-X/index.org][awesome-text-to-x]]
- [[file:2020-01-04-actually-writing-the-tutorial/index.org][Actually writing a programming tutorial]]
- [[file:2019-12-31-writing-programming-tutorials/index.org][Deep dive into tutorial writing]]
- [[file:index.org][El viejo's blog]]