#+TITLE: 

- [[file:inedx.org][El viejo's blog]]
- [[file:index.org][El viejo's blog]]
- 2020-01-04-actually-writing-the-tutorial
  - [[file:2020-01-04-actually-writing-the-tutorial/index.org][Actually writing a programming tutorial]]
- 2019-12-31-writing-programming-tutorials
  - [[file:2019-12-31-writing-programming-tutorials/index.org][Deep dive into tutorial writing]]
- 2020-02-02-Awesome-list-of-text-to-X
  - [[file:2020-02-02-Awesome-list-of-text-to-X/index.org][awesome-text-to-x]]