# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3
        with:
          version: '0.99'

      - name: Install tree, jfq, and mustache
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          npm install --global jfq mustache

      - name: Generate static site
        run: |
          nu -c "tree -I '????-??-??-*' -D --timefmt '%y-%b-%d' -L 3 --sort mtime -r -J --noreport --info | jfq --query-file ./filter-tree-command-append-info.jsonata | tee { mustache ./index.mustache | save --force index.html } | mustache ./rss.mustache | save --force rss.xml"

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Regenerate index.html and rss.xml
          file_pattern: 'index.html rss.xml'

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
